name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Taskwarrior
        run: |
          sudo apt-get update  # Updates the list of available packages and their versions
          sudo apt-get install -y software-properties-common  # Installs utilities for managing software repositories
          sudo add-apt-repository -y ppa:taskwarrior/ppa  # Adds the official Taskwarrior PPA to get the latest version
          sudo apt-get update  # Updates the package list again to include packages from the newly added PPA
          sudo apt-get install -y taskwarrior  # Installs the latest version of Taskwarrior from the added PPA

      - name: Create Taskwarrior config
        run: |
          mkdir -p ~/.task  # Creates the .task directory in the home directory
          echo 'data.location=~/.task' > ~/.taskrc  # Sets data location in .taskrc
          echo 'Confirmation=off' >> ~/.taskrc  # Disables confirmation prompts in .taskrc

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v tests

      - name: Lint code
        run: |
          source venv/bin/activate
          flake8
