name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Taskwarrior
        run: |
          sudo apt-get update
          sudo apt-get install -y taskwarrior

      - name: Create Taskwarrior config
        run: |
          mkdir -p ~/.task  # Creates the .task directory in the home directory
          echo 'data.location=~/.task' > ~/.taskrc  # Sets data location in .taskrc
          echo 'Confirmation=off' >> ~/.taskrc  # Disables confirmation prompts in .taskrc

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v tests

      - name: Lint code
        run: |
          source venv/bin/activate
          flake8
